#!/usr/bin/perl
##############################
# subst_filename - helper utility for the libflux.a makefile
# This file is part of FLUX 2.0 (31-Oct-2007).

$from = shift @ARGV;
$to = shift @ARGV;

open(FILE,"<$from");
open(TOFILE,">$to");

unless($from =~ m/^\// ) {
	chomp($pwd = `pwd`);
	$from = "$pwd/$from";
}

chomp($info = `ls -l $from`);

@lines = <FILE>;
map { s/%%%FILE%%%/$info/o; print TOFILE $_; } @lines;


